# DOROTHY Advanced Training Configuration
# ========================================
# This configuration demonstrates all available options including masking
# and alternative scheduler configurations.

name: robust_desi_model
description: DESI model with masking for improved robustness

# Data configuration
data:
  fits_path: /path/to/your/spectra.fits
  survey: desi
  wavelength_bins: 7650
  input_channels: 2
  train_ratio: 0.7
  val_ratio: 0.2
  quality_filter: true

# Compact model architecture for faster training
model:
  hidden_layers: [2048, 1024, 512, 256, 128]
  normalization: batchnorm
  activation: gelu
  dropout: 0.1                            # Light dropout for regularization

# Training with cosine annealing scheduler
training:
  epochs: 500
  batch_size: 2048
  learning_rate: 0.001
  loss: heteroscedastic
  scatter_floor: 0.01
  gradient_clip: 10.0
  early_stopping_patience: 50             # Stop if no improvement for 50 epochs
  save_every: 50                          # Save checkpoint every 50 epochs

  scheduler:
    type: cosine_annealing
    base_lr: 0.00001
    max_lr: 0.001

# Enable masking for robustness to missing data
masking:
  enabled: true
  mask_fraction: 0.15                     # Mask 15% of wavelengths
  mask_value: 0.0
  contiguous: true                        # Use contiguous regions
  min_region_size: 20                     # Minimum masked region size
  max_region_size: 150                    # Maximum masked region size

output_dir: ./outputs/robust_experiments
seed: 42
device: auto
