# DOROTHY Advanced Training Configuration
# ========================================
# This configuration demonstrates all available options including masking
# and alternative scheduler configurations.

name: robust_desi_model
description: DESI model with masking for improved robustness

# Data configuration
data:
  fits_path: /path/to/your/spectra.fits
  survey: desi
  wavelength_bins: 7650
  input_channels: 2
  train_ratio: 0.7
  val_ratio: 0.2
  quality_filter: true

# Compact model architecture for faster training
model:
  hidden_layers: [2048, 1024, 512, 256, 128]
  normalization: layernorm
  activation: gelu
  dropout: 0.1                            # Light dropout for regularization

# Training with one_cycle scheduler (default) - alternatives: cosine_annealing, cyclic
training:
  epochs: 500
  batch_size: 2048
  learning_rate: 0.001
  loss: heteroscedastic
  scatter_floor: 0.01
  gradient_clip: 10.0
  early_stopping_patience: 50             # Stop if no improvement for 50 epochs
  save_every: 50                          # Save checkpoint every 50 epochs

  # Optimizer (default: AdamW)
  optimizer:
    type: adamw
    weight_decay: 0.01
    betas: [0.9, 0.999]

  scheduler:
    type: one_cycle                       # one_cycle (default), cyclic, cosine_annealing, reduce_on_plateau, none
    max_lr: 0.001
    pct_start: 0.3
    div_factor: 25.0
    final_div_factor: 10000.0

# Enable dynamic input masking for robustness to missing data
input_masking:
  enabled: true
  f_max: 0.3                              # Maximum fraction of wavelengths to mask
  p_block_min: 0.7                        # Min probability of keeping each block
  p_block_max: 0.9                        # Max probability of keeping each block

output_dir: ./outputs/robust_experiments
seed: 42
device: auto
