# DOROTHY Training Configuration: BOSS spectra with APOGEE labels
# This trains a simple MLP to predict stellar parameters from BOSS optical spectra

name: boss_apogee_test

data:
  catalogue_path: data/super_catalogue.h5
  surveys:
    - boss
  label_sources:
    - apogee
  train_ratio: 0.7
  val_ratio: 0.2
  max_flag_bits: 0
  smart_deduplicate: true

model:
  hidden_layers: [2000, 1000, 500, 200, 100]
  normalization: layernorm
  activation: gelu
  dropout: 0.0

training:
  epochs: 10  # Short test run
  batch_size: 512
  learning_rate: 0.001
  loss: heteroscedastic
  gradient_clip: 10.0
  scatter_floor: 0.01
  save_every: 50  # Checkpoint every 50 epochs (adjust epochs for real training)
  scheduler:
    type: one_cycle
    max_lr: 0.001
    pct_start: 0.3
    div_factor: 25.0
    final_div_factor: 10000.0

output_dir: outputs
seed: 42
device: auto
