# DOROTHY Training Configuration - Variant 2
# Multi-Survey Input -> Single Label Source Output
# BOSS + DESI spectra -> APOGEE labels

name: variant2_multi_survey

data:
  catalogue_path: data/super_catalogue.h5
  surveys:
    - boss
    - desi
  label_sources:
    - apogee
  train_ratio: 0.7
  val_ratio: 0.2
  max_flag_bits: -1  # Allow partial labels, per-parameter mask handles validity

# Multi-head MLP for multi-survey training
# survey_wavelengths is auto-populated from the catalogue
multi_head_model:
  latent_dim: 256
  encoder_hidden: [1024, 512]
  trunk_hidden: [512, 256]
  output_hidden: [64]
  combination_mode: concat
  normalization: layernorm
  activation: gelu
  dropout: 0.0

training:
  epochs: 100
  batch_size: 512
  learning_rate: 0.001
  loss: heteroscedastic
  gradient_clip: 10.0
  scatter_floor: 0.01
  save_every: 0
  optimizer:
    type: adamw
    weight_decay: 0.01
  scheduler:
    type: one_cycle
    max_lr: 0.001
    pct_start: 0.3
    div_factor: 100.0
    final_div_factor: 1.0

# Dynamic masking: randomly mask labels during training to improve robustness
label_masking:
  enabled: false
  p_labelset_min: 0.3   # Min prob of keeping each labelset
  p_labelset_max: 1.0   # Max prob of keeping each labelset
  p_label_min: 0.3      # Min prob of keeping each label
  p_label_max: 1.0      # Max prob of keeping each label

# Dynamic masking: randomly mask input spectrum blocks during training
input_masking:
  enabled: false
  p_survey_min: 0.3     # Min prob of keeping each survey
  p_survey_max: 1.0     # Max prob of keeping each survey
  f_max: 0.5            # Max block size as fraction of spectrum
  p_block_min: 0.3      # Min prob of keeping each block
  p_block_max: 1.0      # Max prob of keeping each block

output_dir: outputs
seed: 42
device: auto
