# DOROTHY Training Configuration - Variant 3
# Multi-Survey Input -> Multi-Label Source Output
# LAMOST LRS + LAMOST MRS -> APOGEE + GALAH labels
#
# This variant tests multi-survey sparse training with LAMOST's larger
# datasets (LRS ~100K+ stars, MRS dual-arm spectra).
#
# NOTE: If GALAH labels don't exist in the catalogue, use:
#   duplicate_labels:
#     galah: apogee
# This copies APOGEE labels to create "fake" GALAH labels for testing.

name: variant3_multi_labelset

data:
  catalogue_path: data/super_catalogue_clean.h5
  surveys:
    - lamost_lrs
    - lamost_mrs
  label_sources:
    - apogee
    - galah
  train_ratio: 0.7
  val_ratio: 0.2
  max_flag_bits: 0
  # Duplicate APOGEE labels as GALAH for testing (remove when real GALAH data exists)
  duplicate_labels:
    galah: apogee

# Multi-head MLP for multi-survey, multi-labelset training
# survey_wavelengths and label_sources are auto-populated
multi_head_model:
  latent_dim: 256
  encoder_hidden: [1024, 512]
  trunk_hidden: [512, 256]
  output_hidden: [64]
  combination_mode: concat
  normalization: layernorm
  activation: gelu
  dropout: 0.0

training:
  epochs: 100
  batch_size: 512
  learning_rate: 0.001
  loss: heteroscedastic
  gradient_clip: 10.0
  scatter_floor: 0.01
  save_every: 0
  optimizer:
    type: adamw
    weight_decay: 0.01
  scheduler:
    type: one_cycle
    max_lr: 0.001
    pct_start: 0.3
    div_factor: 100.0
    final_div_factor: 1.0

# Dynamic label masking: hierarchically mask labelsets and individual labels
# Forces the network to learn robust predictions even with incomplete label data
label_masking:
  enabled: true
  p_labelset_min: 0.5   # Min prob of keeping each labelset (apogee, galah)
  p_labelset_max: 1.0   # Max prob of keeping each labelset
  p_label_min: 0.5      # Min prob of keeping each label (teff, logg, etc.)
  p_label_max: 1.0      # Max prob of keeping each label

# Dynamic input masking: hierarchically mask surveys and wavelength blocks
# Forces the network to learn robust predictions with incomplete spectral data
input_masking:
  enabled: true
  p_survey_min: 0.5     # Min prob of keeping each survey (lamost_lrs, lamost_mrs)
  p_survey_max: 1.0     # Max prob of keeping each survey
  f_max: 0.5            # Max block size as fraction of spectrum (log-uniform sampling)
  p_block_min: 0.5      # Min prob of keeping each wavelength block
  p_block_max: 1.0      # Max prob of keeping each block

output_dir: outputs
seed: 42
device: auto
