# DOROTHY Training Configuration - Variant 1
# Single Survey Input -> Single Label Source Output
# BOSS spectra -> APOGEE labels

name: variant1_boss_apogee

data:
  catalogue_path: data/super_catalogue.h5
  surveys:
    - boss
  label_sources:
    - apogee
  train_ratio: 0.7
  val_ratio: 0.2
  max_flag_bits: -1  # Allow partial labels, per-parameter mask handles validity

# Standard MLP with architecture comparable to variant2's multi-head
# variant2 has: encoder [1024,512]->256, trunk [512,256], output [64]->22
# This approximates that flow for single-survey training
model:
  hidden_layers: [1024, 512, 256, 512, 256, 64]
  normalization: layernorm
  activation: gelu
  dropout: 0.0

training:
  epochs: 100
  batch_size: 512
  learning_rate: 0.001
  loss: heteroscedastic
  gradient_clip: 10.0
  scatter_floor: 0.01
  save_every: 0
  optimizer:
    type: adamw
    weight_decay: 0.01
  scheduler:
    type: one_cycle
    max_lr: 0.001
    pct_start: 0.3
    div_factor: 100.0
    final_div_factor: 1.0

output_dir: outputs
seed: 42
device: auto
