# DOROTHY Training Configuration - Variant 4
# All Surveys Input -> Single Label Source Output
# DESI + BOSS + LAMOST LRS + LAMOST MRS -> APOGEE
#
# This variant tests training with all available surveys using APOGEE labels.

name: variant4_all_surveys

data:
  catalogue_path: data/super_catalogue_clean.h5
  surveys:
    - desi
    - boss
    - lamost_lrs
    - lamost_mrs
  label_sources:
    - apogee
  train_ratio: 0.7
  val_ratio: 0.2
  max_flag_bits: 0

# Multi-head MLP for multi-survey, multi-labelset training
# survey_wavelengths and label_sources are auto-populated
multi_head_model:
  latent_dim: 256
  encoder_hidden: [1024, 512]
  trunk_hidden: [512, 256]
  output_hidden: [64]
  combination_mode: concat
  normalization: layernorm
  activation: gelu
  dropout: 0.0

training:
  epochs: 100
  batch_size: 512
  learning_rate: 0.001
  loss: heteroscedastic
  gradient_clip: 10.0
  scatter_floor: 0.01
  save_every: 0
  optimizer:
    type: adamw
    weight_decay: 0.01
  scheduler:
    type: one_cycle
    max_lr: 0.001
    pct_start: 0.3
    div_factor: 100.0
    final_div_factor: 1.0

output_dir: outputs
seed: 42
device: auto
